title: Material Composition
logo: /assets/img/logo.png
description: Material composition is a repository of ideas and techniques that explore materiality through modal synthesis. 
It has been developed by Emiddio Vasquez as part of his PhD research work and makes use of IRCAM's Modalys library
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
